[package]
name = "superdev"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-sdk = "2.3.1"
dotenv = "0.15"
spl-token = "6.0"
spl-associated-token-account = "6.0"
base64 = "0.22"